baseURL = 'https://gopher.run/'
languageCode = 'zh-cn'
title = 'Gopher'

# 启用 Hugo Module
[module]
  [[module.imports]]
    path = "github.com/alex-shpak/hugo-book"

# Book 主题配置
[params]
  # 禁用搜索功能以减少构建复杂度
  BookSearch = true
  # 启用目录
  BookToC = true
  # 启用菜单
  BookMenuBundle = '/menu'
  # 启用代码高亮和复制功能
  BookPortableLinks = true

# 菜单配置
[menu]
  [[menu.before]]
    name = "首页"
    url = "/"
    weight = 10

[markup]
  [markup.highlight]
    style = 'dracula'
    lineNos = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1    # 从H1开始
    endLevel = 4      # 到H4结束
    ordered = false   # 禁用有序列表（数字序号）
